name: Update awesome list

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: star-list
        uses: simonecorsi/mawesome@v2
        with:
          api-token: ${{ secrets.star_ACCESS_TOKEN }}
          github-email: ${{ secrets.USER_EMAIL }}
          template-path: "template/README.ejs"
          github-name: ${{ github.repository_owner }}
